name: Publish Image
on:
  release:
    types:
      - published
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    env:
      context: .
      image_name: swoop-db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install setuptools-scm

      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          VERSION="$(python -m setuptools_scm | tr + -)"
          TAGS=("${VERSION}")

          if [ -n "${{ github.event.release.tag_name }}" ]; then
            MAJOR="$(<<<"${VERSION}" cut -d '.' -f 1)"
            MINOR="${MAJOR}.$(<<<"${VERSION}" cut -d '.' -f 2)"
            TAGS+=('latest' "${MAJOR}" "${MINOR}")
          fi

          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
              TAGS+=("git-${BASH_REMATCH[1]}")
          fi

          for tag in "${TAGS[@]}"; do
              echo ${{ secrets.REGISTRY_REPOSITORY }}/${{ env.image_name }}:${tag}
          done

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.image_tags.outputs.IMAGE_TAGS }}
